import { Jost } from 'next/font/google';
import '@styles/main.scss';

const jost = Jost({
	subsets: ['latin'],
	weight: ['400', '500']
});

export const metadata = {
	title: 'Designo',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={jost.className}>{children}</body>
		</html>
	);
}
