import { Jost } from 'next/font/google';
import '@styles/main.scss';
import Header from '@components/Header/Header';
import Container from '@layout/Container/Container';
import Footer from '@components/Footer/Footer';

const jost = Jost({
	subsets: ['latin'],
	weight: ['400', '500']
});

export const metadata = {
	title: 'Designo',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={jost.className}>
				<Container>
					<Header />
					<main>{children}</main>
				</Container>
				<Footer />
			</body>
		</html>
	);
}
